name: "Publish New Draft Version"

on:
  push:
    tags:
      - "draft-*"

jobs:
  build:
    name: "Publish New Draft Version"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      # See https://github.com/actions/checkout/issues/290
      - name: "Get Tag Annotations"
        run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}

      # Temporarily disabled until the tool is updated to the latest spec
      # - name: "Install and build message generator CLI"
      #   run: cargo build
      #   working-directory: ./tooling/message-generators

      # - name: "Update the message generators in the fixtures folder"
      #   run: ./target/debug/bbs-signature-generator-demo -o file ../fixtures/generators.json
      #   working-directory: ./tooling/message-generators
      
      - name: "Install yarn dependencies"
        run: yarn install --frozen-lockfile
        working-directory: ./tooling/fixtures

      - name: "Populate fixtures Yarn"
        run: yarn populate-fixtures
        working-directory: ./tooling/fixtures

      - name: "Cache Setup"
        id: cache-setup
        run: |
          mkdir -p "$HOME"/.cache/xml2rfc
          echo "::set-output name=path::$HOME/.cache/xml2rfc"
          date -u "+::set-output name=date::%FT%T"
      - name: "Cache References"
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.cache-setup.outputs.path }}
            .targets.mk
          key: refcache-${{ steps.date.outputs.date }}
          restore-keys: |
            refcache-${{ steps.date.outputs.date }}
            refcache-
      - name: "Build Drafts"
        uses: martinthomson/i-d-template@v1
        with:
          token: ${{ github.token }}

      - name: "Upload to Datatracker"
        uses: martinthomson/i-d-template@v1
        with:
          make: upload

      - name: "Archive Submitted Drafts"
        uses: actions/upload-artifact@v2
        with:
          path: "draft-*-[0-9][0-9].xml"
